### PR TITLE
[Fix] User is not able to target hidden menus with TAB

### PR DESCRIPTION
**Pull request by MaksymShokin**
@sofiiakvasnevska

## Issue
Fliplet/fliplet-studio#6420

## Description
Active will change the display from none to block.

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko

### CODE REVIEW

**Comment by tonytlwu** [comment]
@MaksymShokin Can you add a screencast for how the menu expands and collapses before and after this change? I believe the transforms were used to facilitate a smooth animation.

**Comment by MaksymShokin** [comment]
@tonytlwu 
This one actually lost a smooth transition. I will remake this PR.

**Comment by MaksymShokin** [comment]
@tonytlwu Now smooth behaviour works fine.

**Comment by MaksymShokin** [comment]
https://streamable.com/s5m48a

**Comment by MaksymShokin** [comment]
Comparison with production https://streamable.com/ab9f7q

**Review by tonytlwu — APPROVED** [review]
@sofiiakvasnevska This is ready for testing

Risk: Low
Affected: Swipe menu
Verify: Menu opens and closes as expected using mouse, touch gesture and keyboard

**Pull request merged**
